expr                      ::=               term | term "+" expr | term "-" expr
term                      ::=               factor | factor "*" term | factor "/" term
factor                    ::=               identifier | number | "(" expr ")"
number                    ::=               digit | digit number

define                    ::=               identifier [identifier] "=" expr


{
    tokens = [
        number="regexp:\d+"
    ]
}